spring:
  datasource:
    url: jdbc:mysql://kassadin-calm-quest.c5wsjpjjgbjj.eu-north-1.rds.amazonaws.com:3306/calm_quest
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
server:
  port: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

